FROM amazoncorretto:21-alpine

WORKDIR /app

COPY build/libs/spring-petclinic-3.3.0.jar spring-petclinic.jar

EXPOSE 8011

ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
EXPOSE 5005

CMD ["sh", "-c", "java -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:default} spring-petclinic.jar"]
